#!/usr/bin/env python
"""Mechanical checks for a PeoplesHR configuration-document Markdown file.

Usage:
    python check_doc.py <document.md> [--no-screenshots]

--no-screenshots  the developer said there are no screenshots: any image or
                  screenshot/placeholder wording is an ERROR.
--allow-tbd       the developer chose TBD for some items. Without it, any TBD is an ERROR.
Exit code 1 when any ERROR is found. WARN lines need a human decision.
"""
import argparse
import re
import sys
from pathlib import Path

REQUIRED = ["feature_id", "title", "module", "release", "doc_version"]
TBD = "[TBD - confirm with developer]"
TBD_RE = re.compile(r"\[TBD(?: - confirm with developer)?\]")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("markdown")
    ap.add_argument("--no-screenshots", action="store_true")
    ap.add_argument("--allow-internal-urls", action="store_true",
                    help="the developer asked to keep internal links (e.g. Error Catalog Portal)")
    ap.add_argument("--allow-tbd", action="store_true",
                    help="the developer chose TBD for some items; TBD markers become a list, not errors")
    args = ap.parse_args()
    path = Path(args.markdown)
    text = path.read_text(encoding="utf-8")
    errors, warns = [], []

    # ---- front matter
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    meta = {}
    if not m:
        errors.append("Front matter (--- ... ---) missing at top of file.")
        body = text
        offset = 0
    else:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                meta[k.strip()] = v.strip().strip("\"'")
        body = text[m.end():]
        offset = text[: m.end()].count("\n")
        for k in REQUIRED:
            if not meta.get(k):
                errors.append(f"Front matter field '{k}' is empty.")
    lines = body.splitlines()

    # strip fenced code for prose checks
    prose_lines, in_code = [], False
    for ln in lines:
        if ln.strip().startswith("```"):
            in_code = not in_code
            continue
        prose_lines.append("" if in_code else ln)
    prose = "\n".join(prose_lines)

    # ---- file name
    stem = path.stem
    fm = re.match(r"^(\d{2}R\d)-(\d+)-(.+)-(.+)-Doc$", stem)
    if not fm:
        errors.append(f"File name '{stem}' does not match <Release>-<ID>-<Module>-<Title>-Doc.")
    elif meta:
        if meta.get("release") and fm.group(1) != meta["release"]:
            errors.append(f"File name release {fm.group(1)} != front matter release {meta['release']}.")
        if meta.get("feature_id") and fm.group(2) != meta["feature_id"]:
            errors.append(f"File name ID {fm.group(2)} != front matter feature_id {meta['feature_id']}.")
        if meta.get("module") and meta["module"] not in stem:
            warns.append(f"Module '{meta['module']}' does not appear in the file name.")

    # ---- leftover template tokens
    for n, ln in enumerate(lines, 1):
        if "{{" in ln or "}}" in ln:
            errors.append(f"line {n + offset}: unfilled skeleton token: {ln.strip()[:80]}")

    # ---- headings
    headings = [(n, len(h.group(1)), h.group(2).strip()) for n, ln in enumerate(prose_lines, 1)
                if (h := re.match(r"^(#{1,6})\s+(.*)$", ln))]
    seen = set()
    for n, level, title in headings:
        if level > 3:
            errors.append(f"line {n + offset}: heading level {level} not supported (max ###).")
        if re.match(r"^\d+(\.\d+)*\.?\s", title):
            errors.append(f"line {n + offset}: heading is hand-numbered: '{title}'.")
        if "**" in title or title.endswith(":"):
            errors.append(f"line {n + offset}: heading has bold or trailing colon: '{title}'.")
        key = (level, title.lower())
        if key in seen:
            errors.append(f"line {n + offset}: duplicate heading '{title}'.")
        seen.add(key)
    h1 = [t for _, lvl, t in headings if lvl == 1]
    if not h1 or h1[-1].lower() != "change control":
        errors.append("Last top-level section must be '# Change Control'.")
    for required in ("Introduction", "Feature Overview", "Configuration Parameters", "Configuration Procedure"):
        if required.lower() not in [t.lower() for t in h1]:
            errors.append(f"Mandatory section '# {required}' missing.")
    for banned in ("Table of Contents", "Copyright", "Document Control"):
        if banned.lower() in [t.lower() for t in h1]:
            errors.append(f"'# {banned}' is generated by the builder; remove it from the .md.")

    # ---- change control
    cc_idx = next((i for i, ln in enumerate(lines) if re.match(r"^#\s+Change Control\s*$", ln.strip(), re.I)), None)
    if cc_idx is not None:
        rows = [ln for ln in lines[cc_idx + 1:] if ln.strip().startswith("|")]
        data = [r for r in rows[2:] if r.strip("| -")]
        if not data:
            errors.append("Change Control table has no rows.")
        else:
            cells = [c.strip() for c in data[-1].strip().strip("|").split("|")]
            if meta.get("doc_version") and cells and cells[0] != meta["doc_version"]:
                errors.append(f"Last Change Control version {cells[0]} != doc_version {meta['doc_version']}.")
            if len(cells) > 1 and not re.match(r"^\d{2}/\d{2}/\d{4}$", cells[1]) and not TBD_RE.search(cells[1]):
                errors.append(f"Change Control date '{cells[1]}' is not DD/MM/YYYY.")
            for r in data:
                if any(not c.strip() for c in r.strip().strip("|").split("|")):
                    errors.append(f"Change Control row has an empty cell: {r.strip()}")

    # ---- code references and secrets
    checks = [
        (r"\b[\w./\\-]+\.(cs|cshtml|aspx|ascx|vb|js|ts|tsx|css|csproj|sln)\b", "source file reference"),
        (r"\bPR\s*#?\s*\d{3,}|\bpull request\b|\bbranch\b|\bcommit\b", "PR/branch/commit reference"),
        (r"(?i)password\s*=|pwd\s*=|user id\s*=|\bsa;|data source\s*=|server\s*=\s*[\w.\\]+;|instrumentationkey\s*=|accountkey\s*=|api[_ ]?key\s*[=:]|bearer\s+[a-z0-9]", "secret or credential"),
        (r"\b(10|172|192)\.\d{1,3}\.\d{1,3}\.\d{1,3}\b", "internal IP address"),
        (r"dev\.azure\.com|visualstudio\.com|github\.com|sharepoint\.com", "internal URL"),
        (r"\b[A-Z][a-z]+[A-Za-z]*(Controller|DAO|BL)\b", "class name"),
    ]
    for n, ln in enumerate(prose_lines, 1):
        for pattern, label in checks:
            if label == "internal URL" and args.allow_internal_urls:
                continue
            if re.search(pattern, ln):
                errors.append(f"line {n + offset}: {label}: {ln.strip()[:90]}")
    # secrets inside code blocks too
    for n, ln in enumerate(lines, 1):
        if re.search(r"(?i)password\s*=|pwd\s*=", ln) and not prose_lines[n - 1]:
            errors.append(f"line {n + offset}: secret inside code block.")

    # ---- voice
    for n, ln in enumerate(prose_lines, 1):
        low = f" {ln.lower()} "
        for word in (" we ", " our ", " shall ", " we'", "sure!", "here is the", "as an ai"):
            if word in low and not ln.strip().startswith("|  "):
                errors.append(f"line {n + offset}: banned wording '{word.strip()}': {ln.strip()[:90]}")
        if re.search(r"\s(->|→|=>)\s", ln):
            errors.append(f"line {n + offset}: use ' > ' as navigation separator: {ln.strip()[:90]}")
        if re.search(r"\bbehaviour\b|\bcolour\b|\bcustomis", ln, re.I):
            warns.append(f"line {n + offset}: UK spelling (house style is US): {ln.strip()[:60]}")
        if re.search(r"(?i)\b(simply|just|will be able to|obviously)\b", ln):
            warns.append(f"line {n + offset}: filler wording (simply/just/will be able to): {ln.strip()[:80]}")
        if re.search(r"(?i)can be configured\.?\s*\|?\s*$", ln):
            warns.append(f"line {n + offset}: 'can be configured' without saying how.")

    # ---- figures
    figs = [(n, f.group(1), f.group(2)) for n, ln in enumerate(prose_lines, 1)
            if (f := re.match(r"^\s*!\[(.*?)\]\((.*?)\)", ln))]
    if args.no_screenshots:
        for n, _, _ in figs:
            errors.append(f"line {n + offset}: developer said no screenshots, but an image is present.")
        for n, ln in enumerate(prose_lines, 1):
            if re.search(r"(?i)(screenshot|screen shot|image)s?\s+(to be|will be|here|pending|placeholder)|placeholder|\[screenshot|figure \d", ln):
                errors.append(f"line {n + offset}: screenshot/placeholder wording with no screenshots: {ln.strip()[:80]}")
    for expected, (n, cap, src) in enumerate(figs, 1):
        cm = re.match(r"Figure\s+(\d+):\s+\S", cap)
        if not cm:
            errors.append(f"line {n + offset}: caption must be 'Figure N: Sentence.': '{cap}'.")
        elif int(cm.group(1)) != expected:
            errors.append(f"line {n + offset}: figure numbered {cm.group(1)}, expected {expected}.")
        if not (path.parent / src).exists() and not Path(src).exists():
            errors.append(f"line {n + offset}: image file not found: {src}")

    # ---- TBD inventory
    tbds = [(n, ln.strip(), len(TBD_RE.findall(ln))) for n, ln in enumerate(text.splitlines(), 1) if TBD_RE.search(ln)]
    if tbds and not args.allow_tbd:
        errors.append(f"{len(tbds)} line(s) contain TBD. Ask the developer for these facts; "
                      "use --allow-tbd only for items the developer chose to leave TBD.")

    for e in errors:
        print(f"ERROR  {e}")
    for w in warns:
        print(f"WARN   {w}")
    total = sum(c for _, _, c in tbds)
    print(f"\nOpen items: {total} TBD marker(s) on {len(tbds)} line(s) (file line numbers):")
    for n, ln, _ in tbds:
        print(f"  line {n}: {ln[:100]}")
    print(f"\n{len(errors)} error(s), {len(warns)} warning(s).")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
